// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA-yt1TjpHSUG6t-1h9393F9dhrzx5oAQ',
    appId: '1:294012123443:web:51e0172d08513ce1b5e646',
    messagingSenderId: '294012123443',
    projectId: 'tcl-monitor',
    authDomain: 'tcl-monitor.firebaseapp.com',
    storageBucket: 'tcl-monitor.firebasestorage.app',
    measurementId: 'G-PDJKD9DDDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRX00vzMxlykprkRg0OL2iPKaIvSAdSo',
    appId: '1:294012123443:android:a9862d5fea2c018cb5e646',
    messagingSenderId: '294012123443',
    projectId: 'tcl-monitor',
    storageBucket: 'tcl-monitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoIcHs6g7CgX4ZMGE92_JZ1mLrYdfy1us',
    appId: '1:294012123443:ios:927e404c7a89408ab5e646',
    messagingSenderId: '294012123443',
    projectId: 'tcl-monitor',
    storageBucket: 'tcl-monitor.firebasestorage.app',
    iosBundleId: 'pk.com.enigmatek.tclmonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA-yt1TjpHSUG6t-1h9393F9dhrzx5oAQ',
    appId: '1:294012123443:web:1022927ff6db9770b5e646',
    messagingSenderId: '294012123443',
    projectId: 'tcl-monitor',
    authDomain: 'tcl-monitor.firebaseapp.com',
    storageBucket: 'tcl-monitor.firebasestorage.app',
    measurementId: 'G-WFQVKT3TVS',
  );
}
